[theme]
base = "light"
primaryColor = "#27517f"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1c2733"
font = "sans serif"

[server]
headless = true
maxUploadSize = 500

[browser]
gatherUsageStats = false
